### ISSUE TITLE
[QUESTION] - <title>is the poco x3 suitable for nfc

### ISSUE THREAD

**Issue by talha156** [woa-vayu/Port-Windows-11-POCO-X3-Pro#12]
### Question

is the poco x3 suitable for nfc

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by nedokaka** [comment]
@talha156 What

**Comment by bibarub** [comment]
@talha156 doesn't sound like a sensible question to me. please elaborate.

**Comment by halal-beef** [comment]
closed due to inactivity
