### ISSUE TITLE
Machine type missmatch

### ISSUE THREAD

**Issue by gixousiyq** [woa-vayu/Port-Windows-11-POCO-X3-Pro#18]
### Question

**When I write the command:**
`.\driverupdater.exe -d path\to\drivers\definitions\Desktop\ARM64\Internal\vayu_paneltype.txt -r path\to\drivers -p X:`
**with all the paths:**
`C:\Users\crmbo\Desktop\driver-updater\driverupdater.exe -d C:\Users\crmbo\Desktop\Vayu-Drivers-Full\definitions\Desktop\ARM64\Internal\vayu_hauxing.txt -r C:\Users\crmbo\Desktop\Vayu-Drivers-Full -p X:`
**I get this error:**
This version of C:\Users\crmbo\Desktop\driver-updater\driverupdater.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

Any fix?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
You downloaded the arm64 driverupdater, your PC isn't arm64

**Comment by gixousiyq** [comment]
Oh my bad it worked now

**Comment by gixousiyq** [comment]
Oh my bad it worked now
