### ISSUE TITLE
[QUESTION] - what to do when theres no volume named "WINVAYU" after doing "adb shell msc"?

### ISSUE THREAD

**Issue by kusti420** [woa-vayu/Port-Windows-11-POCO-X3-Pro#36]
### Question

no volume named "WINVAYU" are showing up
![image](https://github.com/woa-vayu/Port-Windows-11-POCO-X3-Pro/assets/75937552/a42d4af4-16e7-4260-8603-ca225d5d4fbe)

proof that adb shell msc worked and its showing up
![image](https://github.com/woa-vayu/Port-Windows-11-POCO-X3-Pro/assets/75937552/32edd860-3fc5-4a05-af78-9651e98de9a7)
![image](https://github.com/woa-vayu/Port-Windows-11-POCO-X3-Pro/assets/75937552/a3da94c9-2f66-4617-a08a-9719219a69f2)

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by bibarub** [comment]
well that's because the volume is just not there.
run "partition" again.

**Comment by kusti420** [comment]
mind updating the install instructions then? and by running "partition" again u mean "adb shell msc"?

**Comment by n00b69** [comment]
There is no reason to update the instructions becayse it works fine, you likely forgot to run adb shell partition (properly). If it asks you to run it twice, you have to run it twice.

**Comment by kusti420** [comment]
yes it asked me to run it twice and i did and its still like that

**Comment by bibarub** [comment]
excuse me??
https://github.com/woa-vayu/Port-Windows-11-POCO-X3-Pro/blob/main/guide/install-1-en.md

by "run partition again" i mean exactly what i say: run "adb shell partition", as explained in the first part of the installation guide.

you can't open the second part (which starts with adb shell msc) without completing the first part, unless you've opened the MD file directly, which is by no means our fault.
