### ISSUE TITLE
Cannot make boot files with bcdboot

### ISSUE THREAD

**Issue by Yaroslav-Nesst** [woa-vayu/Port-Windows-11-POCO-X3-Pro#4]
### Question

bcdboot X:\Windows /s Q: /f UEFI
Failure when attempting to copy boot files.
![изображение](https://github.com/woa-vayu/Port-Windows-11-Poco-X3-pro/assets/59181976/c642bbbd-4e9f-42d5-9ca2-c620a7324682)

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by halal-beef** [comment]
@Yaroslav-Nesst Looks like they're already copied, if u want to recopy format drive and do the command again

**Comment by bibarub** [comment]
@Yaroslav-Nesst your ESP partition is too small, you messed up the partition table

**Comment by halal-beef** [comment]
@bibarub True

**Comment by Yaroslav-Nesst** [comment]
> 

but if i flash old partition table from fastboot and do it again, will it work?

**Comment by Yaroslav-Nesst** [comment]
> @Yaroslav-Nesst Looks like they're already copied, if u want to recopy format drive and do the command again

i cant allow testsigning because files dont exist

**Comment by bibarub** [comment]
> > 
> 
> but if i flash old partition table from fastboot and do it again, will it work?

if you do it correctly.

**Comment by Yaroslav-Nesst** [comment]
> > > 
> > 
> > 
> > but if i flash old partition table from fastboot and do it again, will it work?
> 
> if you do it correctly.

![изображение](https://github.com/woa-vayu/Port-Windows-11-Poco-X3-pro/assets/59181976/c165a458-693c-4d82-b4dd-05522df3075e)
this partition table is right?

**Comment by bibarub** [comment]
> > > > 
> > > 
> > > 
> > > but if i flash old partition table from fastboot and do it again, will it work?

it's the stock partition table. now follow the guide carefully and create the needed partitions

**Comment by bibarub** [comment]
> > > > 
> > > 
> > > 
> > > but if i flash old partition table from fastboot and do it again, will it work?
> > 
> > 
> > if you do it correctly.
> 
> ![изображение](https://user-images.githubusercontent.com/59181976/243166301-c165a458-693c-4d82-b4dd-05522df3075e.png) this partition table is right?

it's the stock partition table. now follow the guide carefully and create the needed partitions

**Comment by Yaroslav-Nesst** [comment]
![изображение](https://github.com/woa-vayu/Port-Windows-11-Poco-X3-pro/assets/59181976/6782f8d7-8d5a-4636-b0e5-71639e8f54b7)

**Comment by Yaroslav-Nesst** [comment]
![изображение](https://github.com/woa-vayu/Port-Windows-11-Poco-X3-pro/assets/59181976/8c516465-119d-4984-8d8a-28f46390aea3)

**Comment by bibarub** [comment]
> ![изображение](https://user-images.githubusercontent.com/59181976/243166543-6782f8d7-8d5a-4636-b0e5-71639e8f54b7.png)

you did something wrong again. your ESP partition is barely 2mb, while it should be around 600mb

**Comment by bibarub** [comment]
russian guide is broken. please follow the english guide for now.
