### ISSUE TITLE
Usb not working

### ISSUE THREAD

**Issue by Marius586** [woa-vayu/Port-Windows-11-Poco-X3-pro#5]
### Description

The USB port is not working when connecting a keyboard dongle with an org adapter.
The phone is charging, and when connecting the adapter sometimes appears the charging icon for a split second.

### Reproduction steps

```bash
I'm using tiny11 arm64 from archve.org updated almost at day because last update makes explorer restarting every 5 sec
Drivers from the vayu drivers downloaded with the git clone command
Machine used for installing windows was windows 10. LTSC (if it is related)
Everything done today 19th July
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Phone.
- [X] There is no issue already describing my problem.

**Comment by halal-beef** [comment]
@Marius586 woah

**Comment by bibarub** [comment]
tiny11 is broken don't use it.

**Comment by halal-beef** [comment]
the usb SHOULD work since bibarub enabled host by default

**Comment by Marius586** [comment]
Thanks for the quick response , I'll reinstall tomorrow with the normal windows (in case you do not have any suggestions because I hate stock windows) and for the OTG I tried with it connected when boot but since it seems the was another problem it stil didn't work, thanks again
