### ISSUE TITLE
[QUESTION] - Stuck at Install Windows

### ISSUE THREAD

**Issue by ProcessDuck** [woa-vayu/Port-Windows-11-POCO-X3-Pro#7]
### Question

As i wrote in the title, im stuck on a window named Install Windows. İt says "The computer restarted unexpectedly or encountered an unexpected error. Winows inststallation cannot proceed. To install Windows, click "OK" to restart the computer, and then restart the installation."

İ clicked OK and then it booted to boot menu. i clicked continue boot and the same title and message appeared. İ did this like 5 times and the same title and message appeared. Can someone explain this to me?

### Agreement

- [x] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by bibarub** [comment]
got that a few times earlier. no clue why it happens, try to reinstall windows again

**Comment by ProcessDuck** [comment]
> got that a few times earlier. no clue why it happens, try to reinstall windows again

Ok thanks imma reinstall

**Comment by halal-beef** [comment]
Since I assume ur issue is resolved, this will be closed
